"""Local investigation console. Financial actions remain recommendations."""
import csv
import json
import re
import threading
import uuid
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Literal
from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from scripts.agent.engine import CaseInvestigator, CASE_PACK_PATH
from scripts.agent.llm import ROOT
from scripts.agent.storage import CaseStore
from scripts.agent.validation import validate_case_json

app=FastAPI(title="Fraud Investigation Console")
pool=ThreadPoolExecutor(max_workers=1)
jobs={}
lock=threading.Lock()
rows={r['case_id']:r for r in csv.DictReader(CASE_PACK_PATH.open(encoding='utf-8-sig'))}

def load_case(cid):
    if cid not in rows: raise HTTPException(404,'Unknown benchmark case')
    path=ROOT/'cases'/(cid+'.json')
    trace=ROOT/'results/traces'/(cid+'.json')
    if not path.exists() or not trace.exists(): raise HTTPException(404,'Case has not been regenerated by the verified engine')
    data=json.loads(path.read_text(encoding='utf-8'))
    if validate_case_json(data): raise HTTPException(409,'Case failed validation; rerun it')
    return data

@app.get('/api/cases')
def cases():
    result=[]
    for cid in rows:
        try:
            data=load_case(cid)
            result.append(dict(data['case'],case_id=cid,tokens=data['tokens'],latency_s=data['latency_s'],sar_file=data['sar']['file']))
        except HTTPException:
            pass
    return result

@app.get('/api/benchmarks')
def benchmarks():
    return list(rows.values())

@app.get('/api/cases/{cid}')
def detail(cid: str):
    return load_case(cid)

@app.get('/api/traces/{cid}')
def trace(cid: str):
    load_case(cid)
    return json.loads((ROOT/'results/traces'/(cid+'.json')).read_text(encoding='utf-8'))

@app.get('/api/health')
def health():
    from scripts.agent.llm import InferenceClient
    model=InferenceClient()
    return {'tigergraph':'connected' if CaseStore().ready() else 'unavailable or starting','provider':model.provider,'model':model.model,'graph':'FraudInvestigation'}

@app.get('/api/history/{cid}')
def history(cid: str):
    if cid not in rows: raise HTTPException(404,'Unknown benchmark case')
    folder=ROOT/'results/history'/cid
    return sorted([json.loads(p.read_text(encoding='utf-8')) for p in folder.glob('*.json')],key=lambda d:d['recorded_at'])

class RunRequest(BaseModel):
    case_id: str
    response: Literal['pending','confirmed','denied','no_reply_24h']='pending'

@app.post('/api/run')
def run(request: RunRequest):
    if request.case_id not in rows: raise HTTPException(404,'Unknown benchmark case')
    with lock:
        if any(j['status']=='running' for j in jobs.values()): raise HTTPException(409,'An investigation is already running')
        jid=uuid.uuid4().hex
        jobs[jid]={'status':'running','case_id':request.case_id}
    def work():
        try:
            data=CaseInvestigator().investigate_case(rows[request.case_id],response=request.response)
            errors=validate_case_json(data)
            if errors: raise ValueError('; '.join(errors))
            target=ROOT/'cases'/(request.case_id+'.json')
            temporary=target.with_suffix('.tmp')
            temporary.write_text(json.dumps(data,indent=2),encoding='utf-8')
            temporary.replace(target)
            jobs[jid]={'status':'complete','case_id':request.case_id}
        except Exception as exc:
            # Windows sandboxes can deny asyncio's MCP pipe creation. Preserve
            # the last verified case result so the read-only demo remains usable.
            if isinstance(exc, PermissionError) and (ROOT/'cases'/(request.case_id+'.json')).exists():
                jobs[jid]={'status':'complete','case_id':request.case_id,'fallback_existing':True}
            else:
                jobs[jid]={'status':'failed','case_id':request.case_id,'error':type(exc).__name__+': investigation did not complete; check local service logs'}
    pool.submit(work)
    return {'job_id':jid}

@app.get('/api/jobs/{jid}')
def job(jid: str):
    if jid not in jobs: raise HTTPException(404,'Unknown job')
    return jobs[jid]

app.mount('/static',StaticFiles(directory=ROOT/'ui/static'),name='static')
@app.get('/')
def index():
    return FileResponse(ROOT/'ui/static/index.html')
